# Generated by Django 4.1.2 on 2022-10-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_stock_product_count_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='count',
        ),
    ]
